name: CIPP Development Frontend CI/CD

on:
  push:
    branches:
      - dev

jobs:
  build_and_deploy_job:
    if: github.event.repository.fork == false && github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Dependencies
        run: yarn install

      - name: Build Project
        run: yarn build

      - name: Rename Output Folder
        run: mv out build  # Rename 'out' to 'build' to match Azure's expectations

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_MOSS_0A047A40F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: '/' # App source code path
          api_location: '' # Api source code path - optional
          output_location: 'build' # Change to 'build' after renaming

  close_pull_request_job:
    if: github.event.repository.fork == false && github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_MOSS_0A047A40F }} # change this to your repository secret name
          action: 'close'
